name: highthon_10th_favorite
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  dot_curved_bottom_nav: ^0.0.2
  firebase_auth: ^5.4.2
  firebase_core: ^3.11.0
  flutter:
    sdk: flutter
  flutter_card_swiper: ^7.0.2
  flutter_dotenv: ^5.2.1
  flutter_native_splash: ^2.4.4
  flutter_svg: ^2.0.17
  get: ^4.7.2
  google_sign_in: ^6.2.2
  image_picker: ^1.1.2
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/svgs/
    - assets/images/
    - assets/config/
  fonts:
    - family: Moneygraphy
      fonts: 
        - asset: assets/fonts/Moneygraphy-Rounded.ttf
          weight: 400
